
import { BibleVerse } from '../types';

export const bibleVerses: BibleVerse[] = [
    { ref: "Juan 3:16", text: "Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna." },
    { ref: "Filipenses 4:13", text: "Todo lo puedo en Cristo que me fortalece." },
    { ref: "Salmos 23:1", text: "Jehová es mi pastor; nada me faltará." },
    { ref: "Proverbios 3:5-6", text: "Fíate de Jehová de todo tu corazón, y no te apoyes en tu propia prudencia. Reconócelo en todos tus caminos, y él enderezará tus veredas." },
    { ref: "Romanos 8:28", text: "Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien, esto es, a los que conforme a su propósito son llamados." },
    { ref: "Jeremías 29:11", text: "Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz, y no de mal, para daros el fin que esperáis." },
    { ref: "Mateo 11:28", text: "Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar." },
    { ref: "Isaías 41:10", text: "No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo; siempre te ayudaré, siempre te sustentaré con la diestra de mi justicia." },
    { ref: "1 Corintios 13:4-5", text: "El amor es sufrido, es benigno; el amor no tiene envidia, el amor no es jactancioso, no se envanece; no hace nada indebido, no busca lo suyo, no se irrita, no guarda rencor." },
    { ref: "Salmos 46:1", text: "Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones." },
    { ref: "Josué 1:9", text: "Mira que te mando que te esfuerces y seas valiente; no temas ni desmayes, porque Jehová tu Dios estará contigo en dondequiera que vayas." },
    { ref: "Mateo 6:33", text: "Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas." },
    { ref: "Salmos 91:1-2", text: "El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente. Diré yo a Jehová: Esperanza mía, y castillo mío; mi Dios, en quien confiaré." },
    { ref: "Proverbios 16:3", text: "Encomienda a Jehová tus obras, y tus pensamientos serán afirmados." },
    { ref: "Hebreos 11:1", text: "Es, pues, la fe la certeza de lo que se espera, la convicción de lo que no se ve." },
    { ref: "Romanos 12:2", text: "No os conforméis a este siglo, sino transformaos por medio de la renovación de vuestro entendimiento, para que comprobéis cuál sea la buena voluntad de Dios, agradable y perfecta." },
    { ref: "Santiago 1:2-3", text: "Hermanos míos, tened por sumo gozo cuando os halléis en diversas pruebas, sabiendo que la prueba de vuestra fe produce paciencia." },
    { ref: "1 Juan 4:8", text: "El que no ama, no ha conocido a Dios; porque Dios es amor." },
    { ref: "Efesios 2:8", text: "Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios." },
    { ref: "Salmos 119:105", text: "Lámpara es a mis pies tu palabra, y lumbrera a mi camino." },
    { ref: "Mateo 5:14", text: "Vosotros sois la luz del mundo; una ciudad asentada sobre un monte no se puede esconder." },
    { ref: "Gálatas 5:22-23", text: "Mas el fruto del Espíritu es amor, gozo, paz, paciencia, benignidad, bondad, fe, mansedumbre, templanza; contra tales cosas no hay ley." },
    { ref: "Colosenses 3:23", text: "Y todo lo que hagáis, hacedlo de corazón, como para el Señor y no para los hombres." },
    { ref: "2 Timoteo 1:7", text: "Porque no nos ha dado Dios espíritu de cobardía, sino de poder, de amor y de dominio propio." },
    { ref: "Salmos 34:8", text: "Gustad, y ved que es bueno Jehová; dichoso el hombre que confía en él." },
    { ref: "Proverbios 18:10", text: "Torre fuerte es el nombre de Jehová; a él correrá el justo, y será levantado." },
    { ref: "Isaías 40:31", text: "Pero los que esperan a Jehová tendrán nuevas fuerzas; levantarán alas como las águilas; correrán, y no se cansarán; caminarán, y no se fatigarán." },
    { ref: "Romanos 5:8", text: "Mas Dios muestra su amor para con nosotros, en que siendo aún pecadores, Cristo murió por nosotros." },
    { ref: "Salmos 37:4", text: "Deléitate asimismo en Jehová, y él te concederá las peticiones de tu corazón." },
    { ref: "Mateo 28:20", text: "Y he aquí yo estoy con vosotros todos los días, hasta el fin del mundo." },
    { ref: "Juan 14:6", text: "Jesús le dijo: Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí." },
    { ref: "Romanos 10:9", text: "Que si confesares con tu boca que Jesús es el Señor, y creyeres en tu corazón que Dios le levantó de los muertos, serás salvo." },
    { ref: "Salmos 27:1", text: "Jehová es mi luz y mi salvación; ¿de quién temeré? Jehová es la fortaleza de mi vida; ¿de quién he de atemorizarme?" },
    { ref: "Mateo 5:16", text: "Así alumbre vuestra luz delante de los hombres, para que vean vuestras buenas obras, y glorifiquen a vuestro Padre que está en los cielos." },
    { ref: "Proverbios 22:6", text: "Instruye al niño en su camino, y aun cuando fuere viejo no se apartará de él." },
    { ref: "Hebreos 13:8", text: "Jesucristo es el mismo ayer, y hoy, y por los siglos." },
    { ref: "1 Pedro 5:7", text: "Echando toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros." },
    { ref: "Salmos 103:12", text: "Cuanto está lejos el oriente del occidente, hizo alejar de nosotros nuestras rebeliones." },
    { ref: "Efesios 6:10", text: "Por lo demás, hermanos míos, fortaleceos en el Señor, y en el poder de su fuerza." },
    { ref: "Mateo 7:7", text: "Pedid, y se os dará; buscad, y hallaréis; llamad, y se os abrirá." }
];
